<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Operations;

use \sendpost\sendpost\Utils\SpeakeasyMetadata;
class EmailRouterSendEmailWithTemplateRequest
{
    /**
     * The Email Message
     * 
     * @var string $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=*/*')]
    public string $requestBody;
    
    /**
     * Sub-Account API Key
     * 
     * @var string $xSubAccountApiKey
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-SubAccount-ApiKey')]
    public string $xSubAccountApiKey;
    
	public function __construct()
	{
		$this->requestBody = "";
		$this->xSubAccountApiKey = "";
	}
}
