<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Operations;

use \sendpost\sendpost\Utils\SpeakeasyMetadata;
class EmailRouterSendEmailRequest
{
    /**
     * The Email Message
     * 
     * @var string $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=*/*')]
    public string $requestBody;
    
    /**
     * Mock email header
     * 
     * @var ?bool $xSendPostMockEmail
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-SendPost-Mock-Email')]
    public ?bool $xSendPostMockEmail = null;
    
    /**
     * Mock email time shift
     * 
     * @var ?string $xSendPostMockTimeShift
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-SendPost-Mock-Time-Shift')]
    public ?string $xSendPostMockTimeShift = null;
    
    /**
     * Sub-Account API Key
     * 
     * @var string $xSubAccountApiKey
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-SubAccount-ApiKey')]
    public string $xSubAccountApiKey;
    
	public function __construct()
	{
		$this->requestBody = "";
		$this->xSendPostMockEmail = null;
		$this->xSendPostMockTimeShift = null;
		$this->xSubAccountApiKey = "";
	}
}
