<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Shared;


class Groups
{
	public function __construct()
	{
	}
}
