<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Shared;


class ModelsAttachment
{
	
    public ?string $content = null;
    
	
    public ?string $filename = null;
    
	public function __construct()
	{
		$this->content = null;
		$this->filename = null;
	}
}
