<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Shared;


class ModelsCopyTo
{
	
    public ?CustomFields $customFields = null;
    
	
    public ?string $email = null;
    
	
    public ?string $name = null;
    
	public function __construct()
	{
		$this->customFields = null;
		$this->email = null;
		$this->name = null;
	}
}
