<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Shared;


class ModelsTo
{
    /**
     * $bcc
     * 
     * @var ?array<\sendpost\sendpost\Models\Shared\ModelsCopyTo> $bcc
     */
	
    public ?array $bcc = null;
    
    /**
     * $cc
     * 
     * @var ?array<\sendpost\sendpost\Models\Shared\ModelsCopyTo> $cc
     */
	
    public ?array $cc = null;
    
	
    public ?ModelsToCustomFields $customFields = null;
    
	
    public ?string $email = null;
    
	
    public ?string $name = null;
    
	public function __construct()
	{
		$this->bcc = null;
		$this->cc = null;
		$this->customFields = null;
		$this->email = null;
		$this->name = null;
	}
}
