<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost\Models\Shared;


class ModelsEmailResponse
{
	
    public ?ModelsEmailErrorCode $errorCode = null;
    
	
    public ?string $message = null;
    
	
    public ?string $messageId = null;
    
	
    public ?int $submittedAt = null;
    
	
    public ?string $to = null;
    
	public function __construct()
	{
		$this->errorCode = null;
		$this->message = null;
		$this->messageId = null;
		$this->submittedAt = null;
		$this->to = null;
	}
}
