<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace sendpost\sendpost;

/**
 * Sendpost - SendPost API: Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 * 
 * @package sendpost\sendpost
 * @access public
 */
class Sendpost
{
	public const SERVERS = [
		'/api/v1',
	];
  	
	public SubaccountEmail $subaccountEmail;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return SendpostBuilder
	 */
	public static function builder(): SendpostBuilder
	{
		return new SendpostBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->subaccountEmail = new SubaccountEmail($this->sdkConfiguration);
	}
}